### PR TITLE
Modify ModuleIOSim's motor systems so it doesn't throw exceptions

### LINKED ISSUE #9: ModuleIOSim throws exceptions
When trying to run in sim, drive/ModuleIOSim throws the following exception:
`Error at frc.robot.subsystems.drive.ModuleIOSim.<init>(ModuleIOSim.java:39): Unhandled exception: java.lang.IllegalArgumentException: Ka must be greater than zero.`

If `Ka` is set to be greater than zero, it throws:
`Error at frc.robot.subsystems.drive.ModuleIOSim.<init>(ModuleIOSim.java:39): Unhandled exception: org.ejml.MatrixDimensionException: Malformed measurementStdDevs! Got 1 elements instead of 2`

In short, `Ka` must be greater than zero when setting up a `DCMotorSim` and it must have 2 values for `measurementStdDevs`. The two issues are repeated on line 41. It does not throw an exception if the lines are changed to the following but I'm not sure this is optimal.
```java
private final DCMotorSim driveSim =
      new DCMotorSim(
          LinearSystemId.createDCMotorSystem(0, 0.1), DCMotor.getKrakenX60(0), 0.025, 0.025);
  private final DCMotorSim turnSim =
      new DCMotorSim(
          LinearSystemId.createDCMotorSystem(0, 0.1), DCMotor.getNEO(1), 150.0 / 7.0, 150.0 / 7.0);
```

This issue was found on branch vision and tested on main (with modification to line 19 of Constants to enter sim mode)

### PR DESCRIPTION
**Pull request by TheFlameFish**
Resolve #9, ModuleIOSim throwing exceptions due to changes to `DCMotorSim`'s constructor between WPILib 2024 and 2025. It's a little janky (motors jitter a decent amount and sometimes rotate weirdly) but probably acceptable for simulation.

### CODE REVIEW

**Review by nolanhergert — APPROVED** [review]
Looked "fine" when Ash was driving it around in sim with a controller, other than it acting like it needed to fully rotate the turn motors when reaching some amount of 360 degrees when turning. Hard to describe! Good enough for now though.

File: src/main/java/frc/robot/subsystems/drive/ModuleIOSim.java [hunk 1]
```diff
@@ -36,9 +36,11 @@ public class ModuleIOSim implements ModuleIO {
   private static final double LOOP_PERIOD_SECS = 0.02;
 
   private final DCMotorSim driveSim =
-      new DCMotorSim(LinearSystemId.createDCMotorSystem(0, 0), DCMotor.getKrakenX60(0), 0.025);
+      new DCMotorSim(
+          LinearSystemId.createDCMotorSystem(2.0, 0.01), DCMotor.getKrakenX60(1), 0.025, 0.025);
   private final DCMotorSim turnSim =
-      new DCMotorSim(LinearSystemId.createDCMotorSystem(0, 0), DCMotor.getNEO(1), 150.0 / 7.0);
+      new DCMotorSim(
+          LinearSystemId.createDCMotorSystem(2.0, 0.01), DCMotor.getKrakenX60(1), .004, .004);
```
Comment (Ace5tar) [inline src/main/java/frc/robot/subsystems/drive/ModuleIOSim.java:43]: maybe keep this as 150/7? not sure if its actually better this way though just if there was a reason it was kept as the rational expression

**Review by Ace5tar — APPROVED** [review]

File: src/main/java/frc/robot/subsystems/drive/ModuleIOSim.java (hunk 1 above)
Comment (TheFlameFish) [reply src/main/java/frc/robot/subsystems/drive/ModuleIOSim.java:43]: The value is for stddevs but was previously set to the gear ratio for some reason. Neither I nor Nolan remember why specifically 0.004 was selected though. The full conversation can be found [here](https://github.com/AEMBOT/FRC_2025/issues/9#issuecomment-2645932306).
